[package]
name = "http-libs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
httparse = "*"
syn = "*"
serde = { version = "*", features = ["derive"] }
quote = "*"